### ISSUE TITLE
Hitting on linter links leads to opening of non-existing files

### ISSUE THREAD

**Issue by insiderq** [smeevil/linter-elixir-credo#2]
For example it says that i have an issue in `lib/validate.ex` file. When i hit this message it opens an empty file. If i save that empty file it's saved as `\nlib/validate.ex` (i mean new line symbol at beginning). 
Another empty file is saved as `Compiled lib/controller.ex Compiled lib/...`

**Comment by smeevil** [comment]
Hi @insiderq 

I tried to replicate this problem but did not succeed :/
Would you have an example project or something that would demonstrate this problem ?

Gerard.

**Comment by insiderq** [comment]
Hi, problem disappeared while i was playing with packages. Probably that was from another linter. Sorry for troubling

**Comment by smeevil** [comment]
No problem :) Let me know if you run into anything else :)
