### ISSUE TITLE
Plugin not finding mix

### ISSUE THREAD

**Issue by note89** [smeevil/linter-elixir-credo#7]
When not starting atom from the terminal `linter-elixir-credo` does not find **mix**. 

This probably since the environment variables are not the same. 
Possible solution is to do like `elm-format` or `linter-flow` that lets you add a 

![image](https://cloud.githubusercontent.com/assets/6696963/15635366/38f6c584-25dd-11e6-9d6d-032041247d45.png)

**Comment by smeevil** [comment]
Hi @note89 

I updated the package, it now contains an option in the settings to set the path to mix.
The package now also has an option to pass along flags to credo, curtesy of @sgtpepper43 :)

Let me know if this solves your problem when running atom from a desktop shortcut.

Gerard

**Comment by smeevil** [comment]
@note89 I'll close this for now, if you still run into any problems, let me know !

**Comment by note89** [comment]
Hi i was away for awhile. 
I no longer get the popup error but i also don't get any suggestions from credo. 
If i start via the terminal i still works. 
Maybe i should look into it, given that im the one with the issue. 
I just can't find the time now thou given that i can start it from the terminal and it works just fine :)
